import mongoose from 'mongoose'

const resumeSchema=new mongoose.Schema(
    {
        userId:
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:'User',
            required:true
        },
        title:
        {
            type:String,
            required:true
        },
        thumbNailLink:
        {
            type:String
        },
        template:
        {
            theme:String,
            colorPalette:[String]
        },
        profileInfo:
        {
            profilePreviewUrl: String,
            fullName:String,
            designation:String,
            summary:String
        },
        contactInfo:
        {
            email:String,
            phone:String,
            location:String,
            github:String,
            linkedin:String,
            website:String

        },
        workExperience:[{
            company:String,
            role:String,
            startDate:String,
            endDate:String,
            description:String
        }],
        education:
        [
            {
                degree:String,
                institution:String,
                startDate:String,
                endDate:String,
            },
        ],
        skills:
        [
            {
                name:String,
                property:String,
                progress:Number,
            },
        ],
        projects:
        [
            {
             title:String,
             description:String,
             github:String,
             liveDemo:String
            },
        ],
        certification:
        [
            {
                title:String,
                issuer:String,
                year:String
            }
        ],
        languages:[
            {
                names:String,
                progress:Number,
            },
        ],
        interests:
        [
            
            String
        ],  
    },
    {
        timestamps:
        {
            createdAt:"createdAt",
            updatedAt:"updatedAt",
        }
    }
)
export default mongoose.model("Resume",resumeSchema);
